app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: dbuser
    spring.datasource.password: pass123
    spring.datasource.url: jdbc:postgresql://<DB_SERVER_PUBLIC_IP>:5432/students 

service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar {{ ansible_user_dir }}/spring/target/ds-2025-0.0.1-SNAPSHOT.jar"

