app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: "{{ spring_datasource_username }}"
    spring.datasource.password: "{{ spring_datasource_password }}"
    spring.datasource.url: "{{ spring_datasource_url }}"

service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar {{ ansible_user_dir }}/spring/target/ds-2025-0.0.1-SNAPSHOT.jar"
