app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: "{{ gcloud_spring_datasource_username | default('appuser') }}"
    spring.datasource.password: "{{ gcloud_spring_datasource_password | default('change_me') }}"
    spring.datasource.url: "{{ gcloud_spring_datasource_url | default('jdbc:postgresql://DB_HOST:5432/appdb') }}"

service:
  workingdir: "/home/rg/spring"
  execstart: "java -jar target/springbootdemo-0.0.1-SNAPSHOT.jar"
