appdir: "{{ ansible_user_dir }}/spring"
branch: "main"
appuser: "{{ansible_user_id}}"
appgroup: "{{ansible_user_gid}}"
app_port: 8080
backend_server_url: "http://192.168.56.101:8080"
app:
  VITE_BACKEND:  http://192.168.56.103
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: admin
    spring.datasource.password: admin123
    spring.datasource.url: jdbc:postgresql://db:5432/realestate

