appdir: "{{ ansible_user_dir }}/spring"
branch: "main"
appuser: "{{ansible_user_id}}"
appgroup: "{{ansible_user_gid}}"
app_port: 8080
backend_server_url: "http://192.168.56.101:8080"
app:
  VITE_BACKEND:  http://192.168.56.103
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: dbuser
    spring.datasource.password: IKKqG2jYeLIm01Snfx9qkWfLegPSaZDo
    spring.datasource.url: jdbc:postgresql://dpg-d5hr2i6r433s73buqs00-a.frankfurt-postgres.render.com:5432/dsdb_s6x9

