appdir: "{{ ansible_user_dir }}/spring"
branch: "main"
appuser: "{{ansible_user_id}}"
appgroup: "{{ansible_user_gid}}"
app_port: 8080
app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: "{{ app_spring_datasource_username | default('dbuser') }}"
    spring.datasource.password: "{{ app_spring_datasource_password | default('change_me') }}"
    spring.datasource.url: "{{ app_spring_datasource_url | default('jdbc:postgresql://db:5432/students') }}"

