app_spring_datasource_username: dbuser
app_spring_datasource_password: change_me
app_spring_datasource_url: jdbc:postgresql://db:5432/students
app_postgres_user: dbuser
app_postgres_password: change_me
app_postgres_db: students
